# .github/workflows/terraform-validate.yml

name: Terraform Validate

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  terraform-validate:
    name: Terraform FMT, Init, and Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # Adjust if your .tf files are in a different folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init (no backend config)
        run: terraform init

      - name: Terraform Validate
        run: terraform validate