# .github/workflows/terraform-validate.yml

name: Terraform Validate

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  terraform-validate:
    name: Terraform FMT, Init, and Validate
    runs-on: ubuntu-latest

    container:
      image: alpine/terragrunt

    defaults:
      run:
        working-directory: .  # Adjust if your .tf files are in a different folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Format Check
        run: terraform fmt -check
